Resources:
  Function:
    Type: AWS::Serverless::Function
    Properties:
      Timeout: 300
      MemorySize: 128
      Handler: app.lambda_handler
      CodeUri: C:\Users\Gaurav Pandey\Files\GIT\PinFilter\pin_filter
      Runtime: python3.7
      Architectures:
        - x86_64